import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "@repo/ui/globals.css"
import { AuthProvider } from "@/lib/auth-context"
import Link from "next/link"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
          <Link href="/serverside">Server Side</Link> |{" "}
          <Link href="/">Client Side</Link> | <Link href="/login">Login</Link>
          {children}
        </AuthProvider>
      </body>
    </html>
  )
}
